name: WakaTime Update

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Dependencies
        run: npm install axios dotenv

      - name: Update README with WakaTime stats
        run: node ./scripts/update-wakatime-stats.js
        env:
          WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Docs: Atualiza estatísticas do WakaTime'
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions <actions@github.com>'
