name: Todoist Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-readme-stats:
    name: Atualiza estatísticas do Todoist no README
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        run: node ./scripts/update-todoist-stats.js
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Atualiza estatísticas do Todoist"
          file_pattern: README.md
